server:
  port: 80

spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      routes:
        - id: bookstore
          uri: http://localhost:9090
          predicates:
            - Path=/books/**
        - id: registration
          uri: http://localhost:9091
          predicates:
            - Path=/registration
          filters:
            - RewritePath=/registration, /auth

        - id: token
          uri: http://localhost:9091
          predicates:
            - Path=/login
          filters:
            - RewritePath=/login, /auth/token

        - id: help
          uri: https://spring.io/guides
          predicates:
            - Path=/help
          filters:
            - RedirectTo=302, https://spring.io/guides
